channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.2
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.3.3
  - pyarrow==15.0.2
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env
